#!/bin/sh
# Rebuild an openSUSE package with osc, driven by the %{DISTURL} recorded in the
# original rpm, and write the resulting rpms to $REBUILDERD_OUTDIR.
set -eux

# the file modes of the checkout end up in the source rpm, OBS builds with 022
umask 022

rpmfile="$1"
: "${REBUILDERD_OUTDIR:?}"

query() {
    rpm -qp --nosignature --nodigest --queryformat "$1" "$rpmfile"
}

disturl=$(query '%{DISTURL}')
# the release is generated by OBS, pin it or the rebuilt rpm gets a new filename
release=$(query '%{RELEASE}')
arch=$(query '%{ARCH}')

# obs://<instance>/<project>/<repository>/<srcmd5>-<package>[:<flavor>]
rest=${disturl#obs://}
instance=${rest%%/*}; rest=${rest#*/}
project=${rest%%/*}; rest=${rest#*/}
repository=${rest%%/*}; rest=${rest#*/}
# the srcmd5 is hex only, so the first dash splits it off the package name
package=${rest#*-}
flavor=
case $package in
    *:*)
        flavor=${package#*:}
        package=${package%%:*}
        ;;
esac

# Leap inherits packages from SLE which are built on the internal build.suse.de
if [ "$instance" != "build.opensuse.org" ]; then
    echo "rebuilderd: cannot rebuild ${package}, its sources live on ${instance}" >&2
    exit 1
fi
apiurl="https://api.${instance#build.}"

# noarch rpms don't name a target, build them for the worker's own architecture
if [ "$arch" = "noarch" ]; then
    arch=$(uname -m)
fi

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
cd "$workdir"

# osc parses obs:// urls itself and checks out that exact srcmd5
osc -A "$apiurl" checkout "$disturl"
cd "$project/$package"

# --force because --clean would prompt, and rebuilderd gives us no stdin
# --trust-all-projects because osc would otherwise prompt about signing keys
# SOURCE_DATE_EPOCH and friends come from the project config, don't set them
set -- \
    --clean --force \
    --trust-all-projects \
    --noservice \
    --nochecks \
    --nopreinstallimage \
    --release "$release" \
    --keep-pkgs "$REBUILDERD_OUTDIR" \
    "--build-opt=--disturl=$disturl"
if [ -n "$flavor" ]; then
    set -- "$@" -M "$flavor"
fi
if [ -n "${REBUILDERD_OSC_VM_TYPE:-}" ]; then
    set -- "$@" "--vm-type=$REBUILDERD_OSC_VM_TYPE"
fi

osc -A "$apiurl" build "$@" "$repository" "$arch"
